import { Header } from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en" className={inter.className}>
                <body className="bg-cream flex justify-center">
                    <div className="h-full max-w-[1500px] w-full px-10">
                        <Header />
                        <div>{children}</div>
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
